### ISSUE TITLE
Update AssertJ to at least 3.23 for Matcher Assertions feature

### ISSUE THREAD

**Issue by hiphof** [FontysVenlo/informaticspom#1]
https://github.com/FontysVenlo/informaticspom/blob/d48dec8effdb917b7072fe35405ac1210e60939e/pom.xml#L48

I want to use Matcher Assertions (https://assertj.github.io/doc/#assertj-core-3.23.0-matcher-assertions) for excercise GumballMachine, GumballMachineTest, method toStringTest().

**Comment by Bonajo** [comment]
Done
